export const ActionTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  SELECTED_PRODUCT: 'SELECTED_PRODUCT',
  REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
  ADD_ITEMS: 'ADD_ITEMS',
  DELETE_ITEMS: 'DELETE_ITEMS',
  INCREASE_ITEM: 'INCREASE_ITEM',
  DECREASE_ITEM: 'DECREASE_ITEM',
  TOTAL_ITEMS: 'TOTAL_ITEMS',
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
};
